# Generated by Django 5.2.4 on 2025-09-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sale_date', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.batch', verbose_name='Партия товара')),
            ],
            options={
                'verbose_name': 'Продажа',
                'db_table': 'Продажи',
            },
        ),
    ]
